name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Build static site
        run: echo '<h1>Hello World</h1>' > index.html

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure resources (Bicep)
        run: |
          az deployment group create --resource-group ${{ vars.RESOURCE_GROUP }} --template-file staticwebapp.bicep --parameters staticWebAppName=${{ vars.WEBSITE_NAME }} location=${{ vars.AZURE_LOCATION }}

      - name: 'Deploy to Static Web App'
        run: |
          az staticwebapp upload --name ${{vars.WEBSITE_NAME}} --source . --app-location . --output-location . --verbose
