name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure resources (Bicep)
        run: |
          az deployment group create \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --template-file staticwebapp.bicep \
            --parameters staticWebAppName=${{ vars.WEBSITE_NAME }} \
            --parameters location=${{ vars.AZURE_LOCATION }} \
            --verbose

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "src"
          output_location: "src"
